import { IBook } from "@/type/type";

export const data: { books: IBook[] } = {
  books: [
    {
      id: 1,
      title: "Tom, Dick and Harry",
      count: 1,
      price: 2773,
      desc: "-1E02",
      author: "Brent Washington",
      picUrl: "https://m.media-amazon.com/images/M/MV5BMzcxODlhYjUtYTEzNS00Y2E2LWJlNjctOTVhZTk5ZThmZGU5XkEyXkFqcGdeQXVyNjE4MTE3MDY@._V1_.jpg",
    },
    {
      id: 2,
      title: "Decision at Sundown",
      count: 2,
      price: 3669,
      desc: "'\"'",
      author: "Germaine Minihan",
      picUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRZ2Yt_DUVU_7l0YOpKIHCxN4GKY4vGjEwLZfbUs4-xfR2RMxBV",
    },
    {
      id: 3,
      title: "The Dunwich Horror",
      count: 3,
      price: 1751,
      desc: "œ∑´®†¥¨ˆøπ“‘",
      author: "Ingemar Grimsley",
      picUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcStICyixrPNs5JLO1Pg0O1iLoSPyoo6H8ARw65YxAJqn5jTJS0D",
    },
    {
      id: 4,
      title: "No Name on the Bullet",
      count: 4,
      price: 2362,
      desc: "הָיְתָהtestالصفحات التّحول",
      author: "Liuka Tench",
      picUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRNi-NZC0jSxZ5wmBT1IMC00kpx2w7dEPFKP56olv0wAI-b71lI",
    },
    {
      id: 5,
      title: "Schlussmacher",
      count: 5,
      price: 2474,
      desc: "1.00",
      author: "Cirillo De'Ath",
      picUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRVXggxN4XKFyn4agIlZfS9LqLF7_Hwr7VGS8sVRqQ4CDsY9N62",
    },
    {
      id: 6,
      title: "Big Fella",
      count: 6,
      price: 564,
      desc: "パーティーへ行かないか",
      author: "Reamonn End",
      picUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS7H-txFCrzLn6H2vgbR6gQI5ffOb6SNjoHEr8y4oq3pQopnYka",
    },
    {
      id: 7,
      title: "Europa Report",
      count: 7,
      price: 3793,
      desc: "1E02",
      author: "Merola Swinburn",
      picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpJgpCqrAmiH13Xn5zj86t9vVRm1BXYh6eu19dW84&usqp=CAE&s",
    },
    {
      id: 8,
      title: "The Girl on a Motorcycle",
      count: 8,
      price: 2771,
      desc: "␡",
      author: "Haven Didsbury",
      picUrl: "https://upload.wikimedia.org/wikipedia/en/9/93/The-Girl-on-a-Motocycle.jpg",
    },
    {
      id: 9,
      title: "Maidens' Conspiracy, The (Tirante el Blanco)",
      count: 9,
      price: 3904,
      desc: 'Nice',
      author: "Merralee Thorald",
      picUrl: "https://d3tvwjfge35btc.cloudfront.net/Assets/GalleryImage/15/565/L_g0021656515.jpg",
    },
    {
      id: 10,
      title: "Texas Chainsaw 3D",
      count: 10,
      price: 3620,
      desc: " ",
      author: "Salomi Dight",
      picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHVzBGe8z-tQj2x_IXsPHaHHtOUArR1D_Lq_6rg9k1TZTkVQDU",
    },
  ],
};
